name: build-commit

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Extract short commit hash
        shell: bash
        run: echo "git_hash=$(git rev-parse --short HEAD)" >> $GITHUB_HASH
        id: ref

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Execute Gradle build
        run: ./gradlew shadowJar

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: toggle-keepinv-artifacts-${{ steps.ref.outputs.sha_short }}
          path: build/libs/*.jar
